name: 🏎 Test & Publish Adapter

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.x]

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🦕 Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: ⚡ Run Tests
        run: |
          deno task test
        env:
          CI: true

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🦕 Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: 🥚 Setup Eggy (eggs fork) CLI
        run: |
          deno install -Afq --unstable https://x.nest.land/eggy@0.3.50/cli.ts
          export PATH="/home/runner/.deno/bin:$PATH"
          eggy link ${{ secrets.NESTAPIKEY }}

      - name: 📘 Publish to Nest
        run: |
          eggy publish -Y
